const Mock_Data = [{ "id": 1, "apiName": "Quo Lux", "description": "Charcot's joint, hand", "price": "801", "apiType": "API_FOUR" },
{ "id": 2, "apiName": "Cardify", "description": "Unsp fracture of right acetabulum, subs for fx w routn heal", "price": "958", "apiType": "API_ONE" },
{ "id": 3, "apiName": "Zaam-Dox", "description": "Anaphylactic reaction due to vaccination, sequela", "price": "892", "apiType": "API_THREE" },
{ "id": 4, "apiName": "Quo Lux", "description": "Coma scale, best verbal response, incomprehensible words", "price": "235", "apiType": "API_FOUR" },
{ "id": 5, "apiName": "Fixflex", "description": "Driver of 3-whl mv inj in clsn w unsp mv nontraf, sequela", "price": "210", "apiType": "API_ONE" },
{ "id": 6, "apiName": "Subin", "description": "Familial chondrocalcinosis, right wrist", "price": "952", "apiType": "API_THREE" },
{ "id": 7, "apiName": "Hatity", "description": "Oth fx lower end of left ulna, subs for clos fx w routn heal", "price": "296", "apiType": "API_TWO" },
{ "id": 9, "apiName": "Cardguard", "description": "Legal intervnt w oth sharp objects, suspect injured, sequela", "price": "309", "apiType": "API_TWO" },
{ "id": 10, "apiName": "Ronstring", "description": "Disp fx of less trochanter of l femr, 7thC", "price": "800", "apiType": "API_TWO" },
{ "id": 11, "apiName": "Hatity", "description": "Maternal care for breech presentation", "price": "688", "apiType": "API_ONE" },
{ "id": 12, "apiName": "It", "description": "Spastic entropion of eyelid", "price": "156", "apiType": "API_TWO" },
{ "id": 13, "apiName": "Tampflex", "description": "Subluxation and dislocation of oth parts of shoulder girdle", "price": "357", "apiType": "API_TWO" },
{ "id": 14, "apiName": "It", "description": "Unsp injury of unsp musc/fasc/tend at forearm level", "price": "461", "apiType": "API_THREE" },
{ "id": 16, "apiName": "Temp", "description": "Abnormal dark adaptation curve", "price": "544", "apiType": "API_ONE" },
{ "id": 17, "apiName": "Opela", "description": "Mech compl of internal prosth dev/grft", "price": "463", "apiType": "API_FOUR" },
{ "id": 18, "apiName": "It", "description": "Trib rtnl vein occlusion, right eye, with macular edema", "price": "707", "apiType": "API_ONE" },
{ "id": 19, "apiName": "Sub-Ex", "description": "Corrosion of unsp degree of left lower leg, subs encntr", "price": "424", "apiType": "API_THREE" },
{ "id": 20, "apiName": "Andalax", "description": "Unsp fracture of right femur, subs for clos fx w nonunion", "price": "709", "apiType": "API_ONE" },
{ "id": 21, "apiName": "Y-find", "description": "Torus fx lower end of unsp radius, subs for fx w malunion", "price": "817", "apiType": "API_FOUR" },
{ "id": 22, "apiName": "Tin", "description": "Sprain of unspecified sternoclavicular joint", "price": "448", "apiType": "API_TWO" },
{ "id": 23, "apiName": "Cardguard", "description": "Unspecified superficial injury of forearm", "price": "162", "apiType": "API_FOUR" },
{ "id": 24, "apiName": "Flexidy", "description": "Rheumatoid lung disease w rheumatoid arthritis of unsp wrist", "price": "533", "apiType": "API_TWO" },
{ "id": 25, "apiName": "Cookley", "description": "Oth fx right patella, subs for opn fx type 3A/B/C w nonunion", "price": "072", "apiType": "API_FOUR" },
{ "id": 26, "apiName": "Ventosanzap", "description": "Underdosing of vitamins, subsequent encounter", "price": "275", "apiType": "API_THREE" },
{ "id": 27, "apiName": "Cookley", "description": "Cutaneous follicle center lymphoma", "price": "500", "apiType": "API_TWO" },
{ "id": 28, "apiName": "Fix San", "description": "Laceration without foreign body of nose, sequela", "price": "316", "apiType": "API_TWO" },
{ "id": 29, "apiName": "Sonsing", "description": "Displ commnt fx shaft of r tibia, 7thP", "price": "826", "apiType": "API_TWO" },
{ "id": 30, "apiName": "Sonsing", "description": "Oth nondisp fx of low end unsp humer, subs for fx w malunion", "price": "014", "apiType": "API_TWO" },
{ "id": 31, "apiName": "Otcom", "description": "Corrosion of first degree of lip(s), subsequent encounter", "price": "580", "apiType": "API_FOUR" },
{ "id": 32, "apiName": "Konklux", "description": "Abn cytolog findings in specmn from oth dgstv org/abd cav", "price": "533", "apiType": "API_THREE" },
{ "id": 33, "apiName": "Sub-Ex", "description": "Disp fx of distal pole of navicular bone of left wrist", "price": "526", "apiType": "API_TWO" },
{ "id": 34, "apiName": "Vagram", "description": "Acquired absence of unspecified shoulder", "price": "554", "apiType": "API_TWO" },
{ "id": 35, "apiName": "Tresom", "description": "Passenger of oth sp off-rd mv injured in nontraffic accident", "price": "304", "apiType": "API_ONE" },
{ "id": 36, "apiName": "Solarbreeze", "description": "Prepatellar bursitis", "price": "809", "apiType": "API_TWO" },
{ "id": 37, "apiName": "Sub-Ex", "description": "Toxic effect of herbicides and fungicides, accidental, subs", "price": "083", "apiType": "API_FOUR" },
{ "id": 38, "apiName": "Keylex", "description": "Torus fracture of lower end of left fibula, init for clos fx", "price": "996", "apiType": "API_FOUR" },
{ "id": 39, "apiName": "Sonair", "description": "Other optic atrophy", "price": "905", "apiType": "API_FOUR" },
{ "id": 41, "apiName": "Sub-Ex", "description": "Undrdose of crbnc-anhydr inhibtr, benzo/oth diuretc, sequela", "price": "286", "apiType": "API_FOUR" },
{ "id": 42, "apiName": "Ventosanzap", "description": "Marginal corneal ulcer, unspecified eye", "price": "875", "apiType": "API_ONE" },
{ "id": 43, "apiName": "Ventosanzap", "description": "Nondisp post arch fx 1st cervcal vert, 7thD", "price": "677", "apiType": "API_THREE" },
{ "id": 44, "apiName": "Tempsoft", "description": "Neonatal obstruction of nasolacrimal duct", "price": "164", "apiType": "API_TWO" },
{ "id": 45, "apiName": "Opela", "description": "Patellar tendinitis, unspecified knee", "price": "327", "apiType": "API_TWO" },
{ "id": 47, "apiName": "Lotlux", "description": "Nondisp fx of acromial pro, r shldr, subs for fx w nonunion", "price": "908", "apiType": "API_THREE" },
{ "id": 48, "apiName": "Stringtough", "description": "Poisoning by oth antidysrhythmic drugs, accidental, sequela", "price": "767", "apiType": "API_FOUR" },
{ "id": 49, "apiName": "Rank", "description": "Displ oblique fx shaft of r ulna, 7thR", "price": "363", "apiType": "API_FOUR" },
{ "id": 50, "apiName": "Asoka", "description": "Sltr-haris Type II physeal fx unspecified metatarsal, 7thB", "price": "712", "apiType": "API_ONE" },
{ "id": 51, "apiName": "Otcom", "description": "Parachutist entangled in object", "price": "018", "apiType": "API_FOUR" },
{ "id": 52, "apiName": "Trippledex", "description": "Malignant neoplasm of overlapping sites of left male breast", "price": "226", "apiType": "API_THREE" },
{ "id": 53, "apiName": "Domainer", "description": "Unsp fx fifth metacarpal bone, left hand, init for opn fx", "price": "789", "apiType": "API_FOUR" },
{ "id": 54, "apiName": "It", "description": "Oth traum nondisp spondylolysis of 3rd cervcal vert, 7thK", "price": "077", "apiType": "API_FOUR" },
{ "id": 55, "apiName": "Bitwolf", "description": "Unspecified dislocation of left ring finger, init encntr", "price": "378", "apiType": "API_TWO" },
{ "id": 56, "apiName": "Overhold", "description": "Unspecified disorder of conjunctiva", "price": "626", "apiType": "API_ONE" },
{ "id": 57, "apiName": "Bamity", "description": "Congenital hernia of bladder", "price": "309", "apiType": "API_FOUR" },
{ "id": 58, "apiName": "Trippledex", "description": "Driver of bus injured in nonclsn trnsp acc nontraf, subs", "price": "449", "apiType": "API_THREE" },
{ "id": 59, "apiName": "Tresom", "description": "Strain of musc/fasc/tend triceps, right arm, init", "price": "386", "apiType": "API_TWO" },
{ "id": 60, "apiName": "Viva", "description": "Exposure to natural radiation", "price": "852", "apiType": "API_FOUR" },
{ "id": 61, "apiName": "Keylex", "description": "Displ midcervical fx unsp femur, subs for clos fx w nonunion", "price": "497", "apiType": "API_TWO" },
{ "id": 62, "apiName": "Subin", "description": "Disease of salivary gland, unspecified", "price": "802", "apiType": "API_THREE" },
{ "id": 63, "apiName": "Stronghold", "description": "Unspecified sprain of left little finger, sequela", "price": "015", "apiType": "API_ONE" },
{ "id": 64, "apiName": "It", "description": "Unsp superficial injury of left lesser toe(s), subs encntr", "price": "515", "apiType": "API_FOUR" },
{ "id": 65, "apiName": "Greenlam", "description": "Underdosing of other antidepressants, subsequent encounter", "price": "780", "apiType": "API_THREE" },
{ "id": 67, "apiName": "Regrant", "description": "Oth injury of left internal jugular vein, init encntr", "price": "400", "apiType": "API_TWO" },
{ "id": 68, "apiName": "Span", "description": "Nondisplaced oblique fracture of shaft of left tibia, init", "price": "387", "apiType": "API_ONE" },
{ "id": 69, "apiName": "Zontrax", "description": "Inj muscle, fascia and tendon of triceps, right arm", "price": "189", "apiType": "API_TWO" },
{ "id": 70, "apiName": "Bitchip", "description": "Maternal care for anti-D antibodies, unspecified trimester", "price": "998", "apiType": "API_ONE" },
{ "id": 71, "apiName": "Hatity", "description": "Infect/inflm reaction due to int fix of left fibula, init", "price": "598", "apiType": "API_FOUR" },
{ "id": 72, "apiName": "Overhold", "description": "Stenosis of coronary artery stent, initial encounter", "price": "321", "apiType": "API_ONE" },
{ "id": 73, "apiName": "Pannier", "description": "Other ascites", "price": "779", "apiType": "API_THREE" },
{ "id": 74, "apiName": "Bitchip", "description": "Assault by other hot objects, sequela", "price": "115", "apiType": "API_TWO" },
{ "id": 75, "apiName": "Sub-Ex", "description": "Manic episode in partial remission", "price": "059", "apiType": "API_ONE" },
{ "id": 76, "apiName": "Cookley", "description": "Oth war operations occurring after cessation of hostilities", "price": "758", "apiType": "API_ONE" },
{ "id": 79, "apiName": "Quo Lux", "description": "Other specified fracture of ischium", "price": "191", "apiType": "API_ONE" },
{ "id": 80, "apiName": "Span", "description": "Enteropathic arthropathies, left hand", "price": "325", "apiType": "API_THREE" },
{ "id": 81, "apiName": "It", "description": "Poisoning by therapeutic gases, intentional self-harm", "price": "867", "apiType": "API_THREE" },
{ "id": 82, "apiName": "Wrapsafe", "description": "Crushing injury of unspecified right toe(s), sequela", "price": "904", "apiType": "API_THREE" },
{ "id": 83, "apiName": "Cardify", "description": "Puncture wound with foreign body of penis", "price": "103", "apiType": "API_ONE" },
{ "id": 84, "apiName": "Y-find", "description": "Inj unsp musc/fasc/tend at shldr/up arm, left arm, subs", "price": "730", "apiType": "API_TWO" },
{ "id": 85, "apiName": "Sonair", "description": "Sprain of interphalangeal joint of left ring finger, subs", "price": "137", "apiType": "API_TWO" },
{ "id": 86, "apiName": "Bamity", "description": "Corrosion of third degree of left thumb (nail)", "price": "502", "apiType": "API_ONE" },
{ "id": 88, "apiName": "Redhold", "description": "Other migraine, intractable", "price": "816", "apiType": "API_TWO" },
{ "id": 90, "apiName": "Cookley", "description": "Matern care for damag to fts from viral dis in mother, fts2", "price": "810", "apiType": "API_THREE" },
{ "id": 91, "apiName": "Zoolab", "description": "Encounter for surveillance of contraceptive pills", "price": "611", "apiType": "API_TWO" },
{ "id": 92, "apiName": "Fixflex", "description": "Displaced transverse fx shaft of humerus, left arm, sequela", "price": "503", "apiType": "API_ONE" },
{ "id": 93, "apiName": "Transcof", "description": "Other chondrocalcinosis, right wrist", "price": "314", "apiType": "API_TWO" },
{ "id": 94, "apiName": "Cardify", "description": "Burn of second degree of right palm", "price": "977", "apiType": "API_TWO" },
{ "id": 95, "apiName": "Tres-Zap", "description": "Displaced intertrochanteric fracture of right femur, init", "price": "215", "apiType": "API_THREE" },
{ "id": 96, "apiName": "Bigtax", "description": "Congenital absence of left hand and finger", "price": "347", "apiType": "API_ONE" },
{ "id": 97, "apiName": "Daltfresh", "description": "Unsp subluxation of unspecified shoulder joint, init encntr", "price": "310", "apiType": "API_FOUR" },
{ "id": 98, "apiName": "Bytecard", "description": "Basal cell carcinoma of skin of other parts of face", "price": "826", "apiType": "API_FOUR" },
{ "id": 99, "apiName": "Domainer", "description": "Unsp nondisp fx of 5th cervcal vert, subs for fx w nonunion", "price": "761", "apiType": "API_ONE" },
{ "id": 100, "apiName": "Flowdesk", "description": "Wilson-Mikity syndrome", "price": "977", "apiType": "API_TWO" }
];

export default Mock_Data;